# Generated by Django 3.1.7 on 2021-11-07 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_auto_20211107_1132'),
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='actions.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
